<a href="https://colab.research.google.com/github/gtgindia/Google-Colab-ML/blob/master/Predicting_Employee_Retention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Churn_Modelling.csv',index_col="RowNumber")

In [ ]:
df.head()

CustomerId   Surname  ...  EstimatedSalary Exited
RowNumber                        ...                        
1            15634602  Hargrave  ...        101348.88      1
2            15647311      Hill  ...        112542.58      0
3            15619304      Onio  ...        113931.57      1
4            15701354      Boni  ...         93826.63      0
5            15737888  Mitchell  ...         79084.10      0

[5 rows x 13 columns]

In [ ]:
df.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
df.shape

(10000, 13)

In [ ]:
import numpy as np


In [ ]:
df.isna().sum()

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
x = df.iloc[:, 2:12].values

In [ ]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
y = df.Exited.values

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [ ]:
x = encoder.fit_transform(x)

In [ ]:
x[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [ ]:
x[:,2] = encoder.fit_transform(x[:, 2])

In [ ]:
x = np.asarray(x).astype(np.float32)

In [ ]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [6.0800000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [5.0200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085578e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888523e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190781e+04]], dtype=float32)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train, y_test  = train_test_split(x,y, train_size = 0.75)

In [ ]:
from keras import models
from keras import layers 
model = models.Sequential()
model.add(layers.Dense(1024, activation='relu', input_shape=(16935,))) 
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(8, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))


In [ ]:
x_train.shape[1]

16935

In [ ]:
model.summary()

Model: "sequential_24"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_49 (Dense)             (None, 1024)              17342464  
_________________________________________________________________
dense_50 (Dense)             (None, 256)               262400    
_________________________________________________________________
dense_51 (Dense)             (None, 8)                 2056      
_________________________________________________________________
dense_52 (Dense)             (None, 1)                 9         
Total params: 17,606,929
Trainable params: 17,606,929
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from keras import optimizers 
model.compile(optimizer=optimizers.Adam(), loss='binary_crossentropy', metrics=['accuracy'])


In [ ]:
model.fit(x_train, y_train, batch_size=1024, epochs=15)

Epoch 1/15
7500/7500 [==============================] - 10s 1ms/step - loss: 0.5676 - accuracy: 0.7309
Epoch 2/15
7500/7500 [==============================] - 11s 1ms/step - loss: 0.4330 - accuracy: 0.7972
Epoch 3/15
7500/7500 [==============================] - 10s 1ms/step - loss: 0.3494 - accuracy: 0.7984
Epoch 4/15
7500/7500 [==============================] - 10s 1ms/step - loss: 0.2805 - accuracy: 0.8565
Epoch 5/15
7500/7500 [==============================] - 10s 1ms/step - loss: 0.2207 - accuracy: 0.9412
Epoch 6/15
7500/7500 [==============================] - 10s 1ms/step - loss: 0.1540 - accuracy: 0.9713
Epoch 7/15
7500/7500 [==============================] - 10s 1ms/step - loss: 0.0794 - accuracy: 0.9919
Epoch 8/15
7500/7500 [==============================] - 10s 1ms/step - loss: 0.0252 - accuracy: 0.9976
Epoch 9/15
7500/7500 [==============================] - 11s 1ms/step - loss: 0.0065 - accuracy: 0.9995
Epoch 10/15
7500/7500 [==============================] - 11s 1ms/step - l

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred

array([[1.1591613e-03],
       [5.2179754e-01],
       [5.3523481e-03],
       ...,
       [4.1565739e-04],
       [9.8894823e-01],
       [5.8904937e-03]], dtype=float32)

In [ ]:
y_prediction = (y_pred <= 0.5)

In [ ]:
y_test

array([ True,  True,  True, ...,  True,  True,  True])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_prediction)

In [ ]:
cm

array([[ 309,  207],
       [ 320, 1664]])